python_repo: "https://pypi.tuna.tsinghua.edu.cn/simple"
predefined_node_labels:
  vm-agent: true
default_vars:
  download_run_once: true
  download_localhost: true
  download_force_cache: true
  download_keep_remote_cache: false
  container_manager_on_localhost: 'docker'
  image_command_tool_on_localhost: 'docker'
  calico_vxlan_mode: 'CrossSubnet'
  helm_enabled: true
  ingress_nginx_enabled: true
  ingress_nginx_extra_args:
    - --default-ssl-certificate=default/default-tls
  metrics_server_enabled: true
  krew_enabled: true
  kube_apiserver_node_port_range: "30000-32767"
  ingress_nginx_default: true
configurable_vars:
  - description: "Cache dir for offline install: "
    var:
      download_cache_dir: '/root/kubespray_cache'
  - description: "Enable NTP: "
    var:
      ntp_enabled: true
  - description: "Open firewall rules on each node: "
    var:
      set_firewall_rules: true
  - description: "Containerd insecure registries: "
    var:
      containerd_insecure_registries:
        "nexus-docker-5000:5000": "http://nexus-docker-5000:5000"
  - description: "Install CSI snapshot controller: "
    var:
      csi_snapshot_controller_enabled: true
  - description: "Install NFS client: "
    var:
      install_nfs_client: false
  - description: "Install QEMU: "
    var:
      install_qemu: false
default_mirrors:
  - gcr_image_repo: "gcr.m.daocloud.io"
  - kube_image_repo: "k8s.m.daocloud.io"
  - docker_image_repo: "docker.m.daocloud.io"
  - quay_image_repo: "quay.m.daocloud.io"
  - github_image_repo: "ghcr.m.daocloud.io"
  - files_repo: "https://files.m.daocloud.io"