predefined_node_labels:
  vm-agent: true
  test-label:
default_vars:
  download_run_once: true
  download_localhost: true
  download_force_cache: true
  download_keep_remote_cache: false
  download_cache_dir: /root/kubespray_cache
  container_manager_on_localhost: 'docker'
  image_command_tool_on_localhost: 'docker'
  calico_vxlan_mode: 'CrossSubnet'
  helm_enabled: true
  ingress_nginx_enabled: true
  metrics_server_enabled: true
  krew_enabled: true
  kube_apiserver_node_port_range: "30000-32767"
configuable_vars:
  - description: "Open firewall rules on each node: "
    var:
      set_firewall_rules: true
  - description: "Install NFS client: "
    var:
      install_nfs_client: false
  - description: "Install QEMU: "
    var:
      install_qemu: false
  - description: "Containerd insecure registries: "
    var:
      containerd_insecure_registries:
        "nexus-docker-5000:5000": "http://nexus-docker-5000:5000"
  - description: "String test: "
    var:
      string_test: "a string"
  - description: "Int test: "
    var:
      int_test: 32
default_mirrors:
  - gcr_image_repo: "gcr.m.daocloud.io"
  - kube_image_repo: "k8s.m.daocloud.io"
  - docker_image_repo: "docker.m.daocloud.io"
  - quay_image_repo: "quay.m.daocloud.io"
  - github_image_repo: "ghcr.m.daocloud.io"
  - files_repo: "https://files.m.daocloud.io"