python_repo: "https://pypi.tuna.tsinghua.edu.cn/simple"
predefined_node_labels:
  vm-agent: true
predefined_node_taints:
  - "logging:NoSchedule"
  - "monitoring:NoSchedule"
default_vars:
  download_run_once: true
  download_localhost: true
  download_force_cache: true
  download_keep_remote_cache: false
  container_manager_on_localhost: 'docker'
  image_command_tool_on_localhost: 'docker'
  helm_enabled: true
  ingress_nginx_enabled: true
  ingress_nginx_extra_args:
    - --default-ssl-certificate=default/default-tls
  metrics_server_enabled: true
  krew_enabled: true
  kube_apiserver_node_port_range: "30000-32767"
  ingress_nginx_default: true
  auto_renew_certificates: true
configurable_vars:
  - description: "Cache dir for offline install: "
    var:
      download_cache_dir: '/root/kubespray_cache'
  - description: "Enable NTP: "
    var:
      ntp_enabled: true
  - description: "Open firewall rules on each node: "
    var:
      set_firewall_rules: true
  - description: "Registry mirrors: "
    var:
      containerd_registries_mirrors:
        - prefix: docker.io
          mirrors:
            - host: http://nexus-docker-5000:5000
              capabilities: [ "pull", "resolve" ]
              skip_verify: true
            - host: https://registry-1.docker.io
              capabilities: [ "pull", "resolve" ]
              skip_verify: false
        - prefix: nexus-docker-5001:5001
          mirrors:
            - host: http://nexus-docker-5001:5001
              capabilities: [ "pull", "resolve" ]
              skip_verify: true
  - description: "Install CSI snapshot controller: "
    var:
      csi_snapshot_controller_enabled: true
  - description: "Install NFS client: "
    var:
      install_nfs_client: false
  - description: "Install QEMU: "
    var:
      install_qemu: false
default_mirrors:
  - gcr_image_repo: "gcr.m.daocloud.io"
  - kube_image_repo: "k8s.m.daocloud.io"
  - docker_image_repo: "docker.m.daocloud.io"
  - quay_image_repo: "quay.m.daocloud.io"
  - github_image_repo: "ghcr.m.daocloud.io"
  - files_repo: "https://files.m.daocloud.io"