unsafe_show_logs: true
python_repo: "https://pypi.tuna.tsinghua.edu.cn/simple"
predefined_node_labels:
  zone: "zone1"
predefined_node_taints:
  - "logging:NoSchedule"
  - "monitoring:NoSchedule"
default_vars:
  ansible_python_interpreter: /usr/bin/python3
  download_run_once: true
  download_localhost: true
  download_force_cache: true
  download_keep_remote_cache: true
  download_cache_dir: /root/k8s-installer-offline/kubespray_cache
  container_manager_on_localhost: 'docker'
  image_command_tool_on_localhost: 'docker'
  helm_enabled: true
  ingress_nginx_enabled: true
  ingress_nginx_extra_args:
    - --default-ssl-certificate=default/default-tls
  ingress_nginx_configmap:
    use-forwarded-headers: "false"
  metrics_server_enabled: true
  kube_apiserver_node_port_range: "30000-32767"
  ingress_nginx_default: true
  auto_renew_certificates: true
  etcd_metrics_port: 2381
  etcd_metrics_service_labels:
    k8s-app: etcd
    app.kubernetes.io/managed-by: Kubespray
    app: kube-prometheus-stack-kube-etcd
    release: prometheus
  kube_proxy_metrics_bind_address: "0.0.0.0:10249"
  containerd_use_config_path: true
configurable_vars:
  - description: "Enable NTP: "
    var:
      ntp_enabled: true
  - description: "Open firewall rules on each node: "
    var:
      set_firewall_rules: true
  - description: "Registry mirrors: "
    var:
      containerd_registries_mirrors:
        - prefix: _default
          server: ""
          mirrors:
            - host: http://nexus-docker-5000:5000
              capabilities: [ "pull", "resolve" ]
              skip_verify: true
  - description: "Install k8s-node-watcher: "
    var:
      install_k8s_node_watcher: true
  - description: "Install CSI snapshot controller: "
    var:
      csi_snapshot_controller_enabled: true
  - description: "Install NFS client: "
    var:
      install_nfs_client: false
default_mirrors:
  - gcr_image_repo: "gcr.m.daocloud.io"
  - kube_image_repo: "k8s.m.daocloud.io"
  - docker_image_repo: "docker.m.daocloud.io"
  - quay_image_repo: "quay.m.daocloud.io"
  - github_image_repo: "ghcr.m.daocloud.io"
  - files_repo: "https://files.m.daocloud.io"