---
- name: Check ansible version
  import_playbook: ansible_version.yml

# Install k8s-node-watcher
- hosts: kube_control_plane[0]
  gather_facts: False
  roles:
    - role: kubespray-defaults
      when: install_k8s_node_watcher|default(false)
    - role: k8s-node-watcher
      when: install_k8s_node_watcher|default(false)
