---
- name: Gather host facts to get ansible_os_family
  setup:
    gather_subset: '!all'
    filter: ansible_*

- name: update repositories cache and install NFS
  apt: name=nfs-common update_cache=yes cache_valid_time=3600
  when: "ansible_os_family == 'Debian'"

- name: update repositories cache and install NFS
  yum: name=nfs-utils
  when: "ansible_os_family == 'RedHat'"

- name: Ensure rpcbind is running
  service: name=rpcbind state=started enabled=yes
